### PR TITLE
Fix fallthrough to the next plugin when suitable

### LINKED ISSUE #39: SERVFAIL on fallthrough to forward
When trying to use kubernetai with the following configuration

```
.:53 {
  errors

  kubernetai cluster-a.local in-addr.arpa ip6.arpa {
    fallthrough in-addr.arpa ip6.arpa
    kubeconfig /Users/user/.kube/config arn:aws:eks:us-east-1:000000000000:cluster/a
    pods insecure
  }

  kubernetai cluster-b.local in-addr.arpa ip6.arpa {
    fallthrough in-addr.arpa ip6.arpa
    kubeconfig /Users/user/.kube/config arn:aws:eks:us-east-1:000000000000:cluster/b
    pods insecure
  }

  forward . /etc/resolv.conf {
    max_concurrent 1000
  }
}
```

and using dig to query PTR records of an IP address

```bash
dig @127.0.0.1 -x 1.1.1.1
```

it raises an error saying that the next plugin was not found

```
.:53
CoreDNS-1.8.3
darwin/amd64, go1.16.3, 4293992b-dirty
[ERROR] plugin/errors: 2 1.1.1.1.in-addr.arpa. PTR: plugin/kubernetes: no next plugin found specified
```

and answers the request with SERVFAIL

```
; <<>> DiG 9.10.6 <<>> -x 1.1.1.1 @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 57076
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;1.1.1.1.in-addr.arpa.          IN      PTR

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu May 06 17:11:41 -03 2021
;; MSG SIZE  rcvd: 49
```

instead of using the forward plugin configuration.

### PR DESCRIPTION
**Pull request by t0rr3sp3dr0**
Fixes #39

This patch disables fallthrough on all internal instances of the Kubernetes plugin and lets Kubernetai handle it instead.

Previously the last Kubernetes plugin instance would try to fallthrough and fail as no `Next` plugin instance was set.

### CODE REVIEW

**Comment by t0rr3sp3dr0** [comment]
CicleCI was complaining about missing entries on `go.sum`, so I executed `go mod tidy` and committed the changes.

image

**Comment by t0rr3sp3dr0** [comment]
@chrisohaver, the test is failing because there is no `go.sum` on https://github.com/coredns/ci

**Comment by t0rr3sp3dr0** [comment]
Someone already submitted a PR that creates `go.sum` on the repository, but it hasn't been merged: https://github.com/coredns/ci/pull/139

**Review by rajansandeep — COMMENTED** [review]
I've opened https://github.com/coredns/kubernetai/pull/41 to fix CI.

**Comment by t0rr3sp3dr0** [comment]
I've reverted 0bd9a58 as it wasn't needed.

**Comment by chrisohaver** [comment]
I think this can be even further simplified, by chaining the Kubernetes instances to each other, and setting `Next` on the final instance to the next plugin in the chain (in Add Plugin).  This would allow us to simply call ServeDNS on the first Kubernetes instance, and let the Kubernetes instances themselves handle the fallthrough logic and next plugin chaining.

e.g. something like ...

https://github.com/coredns/kubernetai/compare/master...chrisohaver:fallthufix

**Comment by t0rr3sp3dr0** [comment]
@chrisohaver, I've followed your suggestion with some changes.

The linking procedure between one Kubernetes instance and its successor was moved out of the `Parse` function into the `setup` function.

Additionally, a check was added to ensure that at least one Kubernetes instance always exists. Previously it wasn’t a problem as we used for-loops to iterate over the slice, but now we have direct references to the first element of the slice.

File: plugin/kubernetai/setup.go [hunk 1]
```diff
@@ -44,23 +51,17 @@ func Parse(c *caddy.Controller) (*Kubernetai, error) {
...
 	}
 
-	for i := 0; i < len(k8i.Kubernetes); i++ {
-		// Copy Fallthough settings from the Kubernetes object
-		k8i.Fall = append(k8i.Fall, k8i.Kubernetes[i].Fall)
-		// for all but last instance, disable fallthrough in the Kubernetes object
-		if i < len(k8i.Kubernetes)-1 {
-			k8i.Kubernetes[i].Fall.Zones = nil
-		}
+	if len(k8i.Kubernetes) == 0 {
```
Comment (chrisohaver) [inline plugin/kubernetai/setup.go:63]: Can this condition ever occur?

File: plugin/kubernetai/setup.go [hunk 2]
```diff
@@ -22,16 +23,22 @@ func setup(c *caddy.Controller) error {
...
 
+	prev := &kubernetes.Kubernetes{}
 	for _, k := range k8i.Kubernetes {
 		err = k.InitKubeCache(context.Background())
 		if err != nil {
 			return plugin.Error(Name(), err)
 		}
 		k.RegisterKubeCache(c)
+
+		// set Next of the previous kubernetes stanza to the current stanza
```
Comment (chrisohaver) [inline plugin/kubernetai/setup.go:34]:
```suggestion
		// set Next of the previous kubernetes instance to the current instance
```

**Comment by t0rr3sp3dr0** [comment]
@chrisohaver, I've implemented the tests.

**Review by chrisohaver — APPROVED** [review]
Lgtm Thanks!

**Review by chrisohaver — CHANGES_REQUESTED** [review]
New tests failed.

**Comment by t0rr3sp3dr0** [comment]
I'm not able to reproduce the error. On my machine, the tests are passing. It looks like the tests on CI are trying to connect to the fake API servers that I've specified

image

**Comment by t0rr3sp3dr0** [comment]
Using the same command as the workflow also doesn't throw any error on my side.

image

**Comment by t0rr3sp3dr0** [comment]
I've rebased my branch and now I'm able to reproduce the problem. There was some dependency upgrade on master that is making the test fail. I'll work on it.

**Comment by chrisohaver** [comment]
@t0rr3sp3dr0 I suspect it's due to a bug fixed in coredns/coredns#4492, which is not released yet.

I think we can ignore the failure for now.  It should pass once coredns 1.8.4 is released, and we bump the dependency here.

**Review by chrisohaver — APPROVED** [review]
Thanks for the fix and tests!
